### ISSUE TITLE
Any reason this has not been pushed into core gym environments?

### ISSUE THREAD

**Issue by activatedgeek** [angelolovatto/gym-cartpole-swingup#1]

**Comment by angelolovatto** [comment]
Sorry @activatedgeek, I don't know how I didn't notice this in my notifications. 

In fact, I did try to push this into the core gym environment a long time ago, but got this [response](https://github.com/openai/gym/pull/1590#issuecomment-509316790). 

Sorry for the delay and hope you're enjoying this implementation!
